#!/usr/bin/python3

import sqlite3,sys

if len(sys.argv) < 2 :
  print("Usage:",sys.argv[0],"SUBSTRING-1 SUBSTRING-2 SUBSTRING-3 ...")
  sys.exit(1)

substring_1 = sys.argv[1]
substring_1 = substring_1.replace("'","''")

con = sqlite3.connect('a2.db')

cur = con.cursor()

string = '''
SELECT m.title, m.year, m.content_rating, r.imdb_score, GROUP_CONCAT(DISTINCT g.genre) 
FROM movie m 
LEFT OUTER JOIN rating r on r.movie_id = m.id
LEFT OUTER JOIN acting act ON act.movie_id = m.id 
LEFT OUTER JOIN actor a ON a.id = act.actor_id
LEFT OUTER JOIN director d ON d.id = m.director_id
LEFT OUTER JOIN genre g ON g.movie_id = m.id
WHERE m.title LIKE '%{}%' 
OR a.name LIKE '%{}%'
OR d.name LIKE '%{}%'
GROUP BY m.title, m.year, m.content_rating, r.imdb_score
'''.format(substring_1, substring_1, substring_1)

i = 2
for substring in sys.argv[2:]:
  substring = substring.replace("'","''")
  query = '''
  INTERSECT
  SELECT m.title, m.year, m.content_rating, r.imdb_score, GROUP_CONCAT(DISTINCT g.genre) 
  FROM movie m 
  LEFT OUTER JOIN rating r on r.movie_id = m.id
  LEFT OUTER JOIN acting act ON act.movie_id = m.id 
  LEFT OUTER JOIN actor a ON a.id = act.actor_id
  LEFT OUTER JOIN director d ON d.id = m.director_id
  LEFT OUTER JOIN genre g ON g.movie_id = m.id
  WHERE m.title LIKE '%{}%' 
  OR a.name LIKE '%{}%'
  OR d.name LIKE '%{}%'
  GROUP BY m.title, m.year, m.content_rating, r.imdb_score
  '''.format(substring, substring, substring)

  string = string + query
  i = i + 1

string = string + '\nORDER BY m.year desc, r.imdb_score desc, m.title asc'
cur.execute(string)
i = 1
while True:
  t = cur.fetchone()
  if t == None:
    break
  title,year,rating,score,genre = t
  
  year_rating_score = []
  
  for j in range(1,4):
    if t[j] != None:
      year_rating_score.append(str(t[j]))

  joined = ', '.join([str(item) for item in year_rating_score])
  print('{}. {} ({}) [{}]'.format(i,title, joined, genre))

  i = i + 1

con.close()
